services:
  zerostat:
    build: .
    container_name: zerostat-dashboard
    restart: unless-stopped
    ports:
      - "${ZEROSTAT_PORT:-9124}:${ZEROSTAT_PORT:-9124}"
    environment:
      - ZEROSTAT_PORT=${ZEROSTAT_PORT:-9124}
      - ZEROSTAT_PASSWORD=${ZEROSTAT_PASSWORD:-admin}

    # Required to read accurate host statistics instead of isolating internal container metrics only
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro
      - /var/run/docker.sock:/var/run/docker.sock # Recommended for System Management
      - ./.env:/app/.env
      - ./data:/app/data
